<script setup lang="ts">

</script>

<template>
<div>
  <div data-v-c4b71ab0="" data-v-14565bac="" class="min-w-[180px] max-w-[100%]"><h3 data-v-c4b71ab0="" class="my-8" _msttexthash="13467259" _msthash="55">账户管理</h3><div data-v-c4b71ab0=""><div data-v-c4b71ab0="" class="flex items-center"><div data-v-c4b71ab0="" class="flex-1"><p data-v-c4b71ab0="" _msttexthash="12645594" _msthash="56">账户密码</p><span data-v-c4b71ab0="" class="el-text el-text--info mx-1" _msttexthash="33893821" _msthash="57">当前密码强度：强</span></div><button data-v-c4b71ab0="" aria-disabled="false" type="button" class="el-button el-button--primary is-text"><!--v-if--><span class=""><font _mstmutation="1" _msttexthash="4556994" _msthash="58">修改</font></span></button></div><div data-v-c4b71ab0="" class="el-divider el-divider--horizontal" role="separator" style="--el-border-style: solid;"><!--v-if--></div></div><div data-v-c4b71ab0=""><div data-v-c4b71ab0="" class="flex items-center"><div data-v-c4b71ab0="" class="flex-1"><p data-v-c4b71ab0="" _msttexthash="10643685" _msthash="59">密保手机</p><span data-v-c4b71ab0="" class="el-text el-text--info mx-1" _msttexthash="31305391" _msthash="60">已经绑定手机：158****6789</span></div><button data-v-c4b71ab0="" aria-disabled="false" type="button" class="el-button el-button--primary is-text"><!--v-if--><span class=""><font _mstmutation="1" _msttexthash="4556994" _msthash="61">修改</font></span></button></div><div data-v-c4b71ab0="" class="el-divider el-divider--horizontal" role="separator" style="--el-border-style: solid;"><!--v-if--></div></div><div data-v-c4b71ab0=""><div data-v-c4b71ab0="" class="flex items-center"><div data-v-c4b71ab0="" class="flex-1"><p data-v-c4b71ab0="" _msttexthash="13833248" _msthash="62">密保问题</p><span data-v-c4b71ab0="" class="el-text el-text--info mx-1" _msttexthash="134170023" _msthash="63">未设置密保问题，密保问题可有效保护账户安全</span></div><button data-v-c4b71ab0="" aria-disabled="false" type="button" class="el-button el-button--primary is-text"><!--v-if--><span class=""><font _mstmutation="1" _msttexthash="4556994" _msthash="64">修改</font></span></button></div><div data-v-c4b71ab0="" class="el-divider el-divider--horizontal" role="separator" style="--el-border-style: solid;"><!--v-if--></div></div><div data-v-c4b71ab0=""><div data-v-c4b71ab0="" class="flex items-center"><div data-v-c4b71ab0="" class="flex-1"><p data-v-c4b71ab0="" _msttexthash="13643045" _msthash="65">备用邮箱</p><span data-v-c4b71ab0="" class="el-text el-text--info mx-1" _msttexthash="28135289" _msthash="66">已绑定邮箱：pure***@163.com</span></div><button data-v-c4b71ab0="" aria-disabled="false" type="button" class="el-button el-button--primary is-text"><!--v-if--><span class=""><font _mstmutation="1" _msttexthash="4556994" _msthash="67">修改</font></span></button></div><div data-v-c4b71ab0="" class="el-divider el-divider--horizontal" role="separator" style="--el-border-style: solid;"><!--v-if--></div></div></div>
</div>
</template>

<style scoped>

</style>